version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/rata-project
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create bundle
          command: yarn build
      - store_artifacts:
          path: ~/rata-project/dist
