import React from 'react';
import { Module } from '../../../core/module';
import { onModuleActivate } from '../../utils';
import { createNext } from './utils';

const values = [
  { val1: 'i', val2: 'y' },
  { val1: 'í', val2: 'ý' },
];

// http://www.zlobidlo.cz/rodice/cviceni-vyjmenovana-slova-s
export const dictionary = [
  { text: 's_té jídlo', valIdx: 0, correct: 'y' },
  { text: 's_chravý podzim', valIdx: 0, correct: 'y' },
  { text: 'můj s_novec', valIdx: 0, correct: 'y' },
  { text: 'syn us_ná sám', valIdx: 1, correct: 'í' },
  { text: 's_n usíná sám', valIdx: 0, correct: 'y' },
  { text: 'malá síň je s_ňka', valIdx: 1, correct: 'í' },
  { text: 'malá s_ň je síňka', valIdx: 1, correct: 'í' },
  { text: 's_lonová taška', valIdx: 0, correct: 'i' },
  { text: 's_slí doupě', valIdx: 0, correct: 'y' },
  { text: 'vys_chá mu v ústech', valIdx: 0, correct: 'y' },
  { text: 's_kora koňadra', valIdx: 1, correct: 'ý' },
  { text: 'os_pal se vyrážkou', valIdx: 0, correct: 'y' },
  { text: 's_rová mrkev', valIdx: 0, correct: 'y' },
  { text: 'myš má ráda s_r', valIdx: 1, correct: 'ý' },
  { text: 'volejbalová s_ť', valIdx: 1, correct: 'í' },
  { text: 'plísňový s_r', valIdx: 1, correct: 'ý' },
  { text: 'staré s_dliště', valIdx: 1, correct: 'í' },
  { text: 'máš velikou s_lu', valIdx: 1, correct: 'í' },
  { text: 'zas_pat díru', valIdx: 0, correct: 'y' },
  { text: 'nos_t batoh', valIdx: 0, correct: 'i' },
  { text: 's_pký písek', valIdx: 0, correct: 'y' },
  { text: 'kvalitní s_rečky', valIdx: 0, correct: 'y' },
  { text: 'prádlo us_chá', valIdx: 0, correct: 'y' },
  { text: 's_lný chlapík', valIdx: 0, correct: 'i' },
  { text: 'us_chající tráva', valIdx: 0, correct: 'y' },
  { text: 'nerozs_pej mouku', valIdx: 0, correct: 'y' },
  { text: 's_korčino hnízdo', valIdx: 1, correct: 'ý' },
  { text: 'dos_ta se najedl', valIdx: 0, correct: 'y' },
  { text: 's_náček spinká', valIdx: 0, correct: 'y' },
  { text: 'přes_pej cukr', valIdx: 0, correct: 'y' },
  { text: 'nové s_tko', valIdx: 1, correct: 'í' },
  { text: 'chladný měs_c', valIdx: 1, correct: 'í' },
  { text: 'nemus_š kreslit', valIdx: 1, correct: 'í' },
  { text: 's_ček houkal', valIdx: 1, correct: 'ý' },
  { text: 'prezidentské s_dlo', valIdx: 1, correct: 'í' },
  { text: 'os_ka se třepe', valIdx: 0, correct: 'i' },
  { text: 'mas_té jídlo', valIdx: 0, correct: 'i' },
  { text: 's_rovátka', valIdx: 0, correct: 'y' },
  { text: 'pomazánka se s_rem', valIdx: 1, correct: 'ý' },
  { text: 's_vá holubička', valIdx: 0, correct: 'i' },
  { text: 'pára s_čela', valIdx: 0, correct: 'y' },
  { text: 'chraptíš a s_peš', valIdx: 1, correct: 'í' },
  { text: 'nás_lí', valIdx: 0, correct: 'i' },
  { text: 'malý les je les_k', valIdx: 1, correct: 'í' },
  { text: 'paní S_korová', valIdx: 1, correct: 'ý' },
  { text: 'děravé s_to', valIdx: 1, correct: 'í' },
  { text: 'pros_vá písek', valIdx: 1, correct: 'í' },
  { text: 'malá předs_ň', valIdx: 1, correct: 'í' },
  { text: 's_novec Milan', valIdx: 0, correct: 'y' },
  { text: 'nes_čkuj', valIdx: 1, correct: 'ý' },
  { text: 'dětský zás_p', valIdx: 0, correct: 'y' },
  { text: 's_dlo vlády', valIdx: 1, correct: 'í' },
  { text: 's_ra je nerost', valIdx: 1, correct: 'í' },
  { text: 'dej mi kus s_ra', valIdx: 1, correct: 'ý' },
  { text: 'máma us_ná pozdě', valIdx: 1, correct: 'í' },
  { text: 'hlas_tá hudba', valIdx: 0, correct: 'i' },
  { text: 'nejs_lnější kluk', valIdx: 0, correct: 'i' },
  { text: 's_lný uragán', valIdx: 0, correct: 'i' },
  { text: 'kaluže vys_chají', valIdx: 0, correct: 'y' },
  { text: 's_rový brambor', valIdx: 0, correct: 'y' },
  { text: 'olomoucký s_reček', valIdx: 0, correct: 'y' },
  { text: 'jahodový s_rup', valIdx: 0, correct: 'i' },
  { text: 'velké ús_lí', valIdx: 0, correct: 'i' },
  { text: 's_pký sníh', valIdx: 0, correct: 'y' },
  { text: 's_lonové vlákno', valIdx: 0, correct: 'i' },
  { text: 'klikatá s_lnice', valIdx: 0, correct: 'i' },
  { text: 'os_řelé dítě', valIdx: 0, correct: 'i' },
  { text: 'zmije zas_čela', valIdx: 0, correct: 'y' },
  { text: 'plachá las_čka', valIdx: 0, correct: 'i' },
  { text: 'úzká s_lnice', valIdx: 0, correct: 'i' },
  { text: 'listí na os_ce', valIdx: 0, correct: 'i' },
  { text: 'mladý s_sel', valIdx: 0, correct: 'y' },
  { text: 'vys_lující horko', valIdx: 0, correct: 'i' },
  { text: 'nefunkční vys_lačka', valIdx: 1, correct: 'í' },
  { text: 'otec se s_nem', valIdx: 0, correct: 'y' },
  { text: 'déšť zes_lil', valIdx: 1, correct: 'í' },
  { text: 'vánoční bes_dka', valIdx: 1, correct: 'í' },
  { text: 'druhé tis_ciletí', valIdx: 0, correct: 'i' },
  { text: 'bláto os_chá', valIdx: 0, correct: 'y' },
  { text: 'naplnit s_pky', valIdx: 1, correct: 'ý' },
  { text: 'jsi nenas_ta', valIdx: 0, correct: 'y' },
  { text: 's_rové výpary', valIdx: 1, correct: 'í' },
  { text: 'chytil se do s_tě', valIdx: 1, correct: 'í' },
  { text: 'obs_paná květy', valIdx: 0, correct: 'y' },
  { text: 'rozs_pané časopisy', valIdx: 0, correct: 'y' },
  { text: 'rovná s_lnice', valIdx: 0, correct: 'i' },
  { text: 'kozí s_r', valIdx: 1, correct: 'ý' },
  { text: 'přes_pací hodiny', valIdx: 1, correct: 'ý' },
  { text: 's_dlící ptáci', valIdx: 1, correct: 'í' },
  { text: 'had s_čí', valIdx: 0, correct: 'y' },
  { text: 'rozs_paná sůl', valIdx: 0, correct: 'y' },
  { text: 'sypej s_korkám zrní', valIdx: 1, correct: 'ý' },
  { text: 's_pej sýkorkám zrní', valIdx: 0, correct: 'y' },
  { text: 'neos_dlené oblasti', valIdx: 1, correct: 'í' },
  { text: 'studna vys_chá', valIdx: 0, correct: 'y' },
  { text: 'hlasitý s_kot', valIdx: 0, correct: 'y' },
  { text: 'hlas_tý sykot', valIdx: 0, correct: 'i' },
  { text: 'malý syn je s_náček', valIdx: 0, correct: 'y' },
  { text: 'malý s_n je synáček', valIdx: 0, correct: 'y' },
  { text: 'mluví - sotva s_pe', valIdx: 1, correct: 'í' },
  { text: 'synovec us_ná sám', valIdx: 1, correct: 'í' },
  { text: 's_novec usíná sám', valIdx: 0, correct: 'y' },
  { text: 's_tko na čaj', valIdx: 1, correct: 'í' },
  { text: 'pros_me o radu', valIdx: 1, correct: 'í' },
  { text: 'rybičky v s_ti', valIdx: 1, correct: 'í' },
  { text: 's_lný slon', valIdx: 0, correct: 'i' },
];

const View = ({ options }) => (<div className="problem">{dictionary[options.i].text}</div>);

// method of selecting questions: 0: pick from 'wrong' array, 1: pick from 'slow' array, 2: generate new
// method with higher number is always fallback for the current one
const methods = [0, 0, 1, 2];

export const wIYs = new Module({
  routeName: 'w-iy-s',
  title: 'i/y po S',
  subtitle: 'vyjmenovaná slova',
  onActivate: onModuleActivate,
  next: createNext(dictionary, values, methods),
  View,
});
