import React from 'react';
import { Module } from '../../../core/module';
import { onModuleActivate } from '../../utils';
import { createNext } from './utils';

const values = [
  { val1: 'i', val2: 'y' },
  { val1: 'í', val2: 'ý' },
];

// http://www.zlobidlo.cz/rodice/cviceni-vyjmenovana-slova-v
export const dictionary = [
  { text: 'v_strašený pes', valIdx: 0, correct: 'y' },
  { text: 'stará v_dlička', valIdx: 0, correct: 'i' },
  { text: 'můj zlozv_k', valIdx: 0, correct: 'y' },
  { text: 'v_tat babičku', valIdx: 1, correct: 'í' },
  { text: 'malá v_ska', valIdx: 1, correct: 'í' },
  { text: 'v_dět vinohrad', valIdx: 0, correct: 'i' },
  { text: 'vidět v_nohrad', valIdx: 0, correct: 'i' },
  { text: 'skok do v_šin', valIdx: 1, correct: 'ý' },
  { text: 'pán z V_sočan', valIdx: 0, correct: 'y' },
  { text: 'vlk v_je', valIdx: 0, correct: 'y' },
  { text: 'nové prav_tko', valIdx: 1, correct: 'í' },
  { text: 'v_soká věž', valIdx: 0, correct: 'y' },
  { text: 'v_rábět hračky', valIdx: 0, correct: 'y' },
  { text: 'neobv_klý stav', valIdx: 0, correct: 'y' },
  { text: 'zv_kal si těžko', valIdx: 0, correct: 'y' },
  { text: 'dobře v_dět', valIdx: 0, correct: 'i' },
  { text: 'řeka V_dra', valIdx: 0, correct: 'y' },
  { text: 'zimní v_prodej', valIdx: 1, correct: 'ý' },
  { text: 'lidový v_pravěč', valIdx: 0, correct: 'y' },
  { text: 'nejv_šší hora', valIdx: 0, correct: 'y' },
  { text: 'školní v_let', valIdx: 1, correct: 'ý' },
  { text: 'v_borná polévka', valIdx: 1, correct: 'ý' },
  { text: 'v_borný student', valIdx: 1, correct: 'ý' },
  { text: 'těžké v_ko', valIdx: 1, correct: 'í' },
  { text: 'oční v_čko', valIdx: 1, correct: 'í' },
  { text: 'nepov_kuj', valIdx: 0, correct: 'y' },
  { text: 'spravený v_tah', valIdx: 1, correct: 'ý' },
  { text: 'dnešní nov_ny', valIdx: 0, correct: 'i' },
  { text: 'v_r je sova', valIdx: 1, correct: 'ý' },
  { text: 'vodní v_r', valIdx: 1, correct: 'í' },
  { text: 'táhlá v_šina', valIdx: 1, correct: 'ý' },
  { text: 'nadmořská v_ška', valIdx: 1, correct: 'ý' },
  { text: 'v_letníci jdou', valIdx: 1, correct: 'ý' },
  { text: 'špatné náv_ky', valIdx: 0, correct: 'y' },
  { text: 'cesta se v_ne', valIdx: 0, correct: 'i' },
  { text: 'jedu na V_sočinu', valIdx: 0, correct: 'y' },
  { text: 'v_šší princip', valIdx: 0, correct: 'y' },
  { text: 'nevyv_šuj se', valIdx: 0, correct: 'y' },
  { text: 'nev_vyšuj se', valIdx: 0, correct: 'y' },
  { text: 'nebuď v_strašený', valIdx: 0, correct: 'y' },
  { text: 'v_tat kamaráda', valIdx: 1, correct: 'í' },
  { text: 'třídní v_kaz', valIdx: 1, correct: 'ý' },
  { text: 'klíčový v_sledek', valIdx: 1, correct: 'ý' },
  { text: 'v_braný spis', valIdx: 0, correct: 'y' },
  { text: 'to je v_mysl', valIdx: 1, correct: 'ý' },
  { text: 'dívka v_je věneček', valIdx: 0, correct: 'i' },
  { text: 'malá mořská v_la', valIdx: 1, correct: 'í' },
  { text: 'v_ská tě ve vlasech', valIdx: 1, correct: 'í' },
  { text: 'v_dáme se často', valIdx: 1, correct: 'í' },
  { text: 'létat v_š', valIdx: 1, correct: 'ý' },
  { text: 'víš v_sledek', valIdx: 1, correct: 'ý' },
  { text: 'v_š výsledek', valIdx: 1, correct: 'í' },
  { text: 'v_stavěl dům', valIdx: 0, correct: 'y' },
  { text: 'nová v_la', valIdx: 0, correct: 'i' },
  { text: 'v_dří kožich', valIdx: 0, correct: 'y' },
  { text: 'V_deň', valIdx: 1, correct: 'í' },
  { text: 'v_dám peníze', valIdx: 0, correct: 'y' },
  { text: 'jsi v_nen', valIdx: 0, correct: 'i' },
  { text: 'silná v_chřice', valIdx: 0, correct: 'i' },
  { text: 'můj bratr V_ktor', valIdx: 0, correct: 'i' },
  { text: 'slunce v_chází', valIdx: 0, correct: 'y' },
  { text: 'vycpaná v_dra', valIdx: 0, correct: 'y' },
  { text: 'v_cpaná vydra', valIdx: 0, correct: 'y' },
  { text: 'z v_šiny', valIdx: 1, correct: 'ý' },
  { text: 'malá v_ska', valIdx: 1, correct: 'í' },
  { text: 'v_sel za nohy', valIdx: 0, correct: 'i' },
  { text: 'v_dali časopis', valIdx: 0, correct: 'y' },
  { text: 'pan V_hlídal', valIdx: 0, correct: 'y' },
  { text: 'v_tí psů', valIdx: 0, correct: 'y' },
  { text: 'vítr zv_řil prach', valIdx: 1, correct: 'í' },
  { text: 'v_tr zvířil prach', valIdx: 1, correct: 'í' },
  { text: 'holka v_rostla', valIdx: 0, correct: 'y' },
  { text: 'začni jim v_kat', valIdx: 0, correct: 'y' },
  { text: 'náročný v_klad', valIdx: 1, correct: 'ý' },
  { text: 'zub se v_klá', valIdx: 0, correct: 'i' },
  { text: 'vojenský v_cvik', valIdx: 1, correct: 'ý' },
  { text: 'vojenský výcv_k', valIdx: 0, correct: 'i' },
  { text: 'udělej v_myk', valIdx: 1, correct: 'ý' },
  { text: 'v_měna známek', valIdx: 1, correct: 'ý' },
  { text: 'nový v_kýř', valIdx: 0, correct: 'i' },
  { text: 'v_myj sklenici', valIdx: 0, correct: 'y' },
  { text: 'v_hoď odpadky', valIdx: 0, correct: 'y' },
  { text: 'novinový v_tisk', valIdx: 1, correct: 'ý' },
  { text: 'přiv_dělek', valIdx: 1, correct: 'ý' },
  { text: 'hradní v_žka', valIdx: 1, correct: 'í' },
  { text: 'v_ří houkání', valIdx: 1, correct: 'ý' },
  { text: 'rozv_jet se', valIdx: 1, correct: 'í' },
  { text: 'v_šehradská skála', valIdx: 0, correct: 'y' },
  { text: 'nezav_rej oči', valIdx: 1, correct: 'í' },
  { text: 'otev_rej pomalu', valIdx: 1, correct: 'í' },
  { text: 'jsi v_těz', valIdx: 1, correct: 'í' },
  { text: 'výborné v_svědčení', valIdx: 0, correct: 'y' },
  { text: 'v_borné vysvědčení', valIdx: 1, correct: 'ý' },
  { text: 'můj kamarád V_tek', valIdx: 1, correct: 'í' },
  { text: 'vylov_t rybičku', valIdx: 0, correct: 'i' },
  { text: 'v_lovit rybičku', valIdx: 0, correct: 'y' },
  { text: 'v_la v pohádkách', valIdx: 1, correct: 'í' },
  { text: 'v_sej mák', valIdx: 0, correct: 'y' },
  { text: 'v_dat knihy', valIdx: 0, correct: 'y' },
  { text: 'v_dali jsme se', valIdx: 1, correct: 'í' },
  { text: 'v_maluj omalovánku', valIdx: 0, correct: 'y' },
  { text: 'v_piš složenku', valIdx: 0, correct: 'y' },
  { text: 'v_tři kuchyň', valIdx: 0, correct: 'y' },
  { text: 'brzy si zv_kneš', valIdx: 0, correct: 'y' },
  { text: 'záv_st', valIdx: 0, correct: 'i' },
  { text: 'nepřežv_kuj', valIdx: 0, correct: 'y' },
  { text: 'všechno znáš a v_š', valIdx: 1, correct: 'í' },
  { text: 'severní v_tr', valIdx: 1, correct: 'í' },
  { text: 'dlouhá chv_le', valIdx: 1, correct: 'í' },
  { text: 'to je ale v_heň', valIdx: 1, correct: 'ý' },
  { text: 'v_měnit za lepší', valIdx: 0, correct: 'y' },
  { text: 'zv_kat si', valIdx: 0, correct: 'y' },
  { text: 'mentolová žv_kačka', valIdx: 1, correct: 'ý' },
  { text: 'v_soký panelák', valIdx: 0, correct: 'y' },
  { text: 'hubený jako v_žle', valIdx: 0, correct: 'y' },
  { text: 'v_kázat ven', valIdx: 0, correct: 'y' },
  { text: 'dětský pov_k', valIdx: 0, correct: 'y' },
  { text: 'v_klají se zuby', valIdx: 0, correct: 'i' },
  { text: 'v_ří zobák', valIdx: 1, correct: 'ý' },
  { text: 'v_loha je vyzdobená', valIdx: 1, correct: 'ý' },
  { text: 'výloha je v_zdobená', valIdx: 0, correct: 'y' },
  { text: 'zralé v_šně', valIdx: 0, correct: 'i' },
  { text: 'hroznové v_no', valIdx: 1, correct: 'í' },
  { text: 'v_stavené obrazy', valIdx: 0, correct: 'y' },
  { text: 'v_deňský kostel', valIdx: 1, correct: 'í' },
  { text: 'v_sutá lanovka', valIdx: 0, correct: 'i' },
  { text: 'obrazy v_sely rovně', valIdx: 0, correct: 'i' },
];

const View = ({ options }) => (<div className="problem">{dictionary[options.i].text}</div>);

// method of selecting questions: 0: pick from 'wrong' array, 1: pick from 'slow' array, 2: generate new
// method with higher number is always fallback for the current one
const methods = [0, 0, 1, 2];

export const wIYv = new Module({
  routeName: 'w-iy-v',
  title: 'i/y po V',
  subtitle: 'vyjmenovaná slova',
  onActivate: onModuleActivate,
  next: createNext(dictionary, methods),
  View,
  correctResp: ({ i }) => (dictionary[i].correct),
  choices: ({ i }) => (values[dictionary[i].valIdx]),
});
