import React from 'react';
import { Module } from '../../../core/module';
import { onModuleActivate } from '../../utils';
import { createNext } from './utils';

const values = [
  { val1: 'i', val2: 'y' },
  { val1: 'í', val2: 'ý' },
];

// http://www.zlobidlo.cz/rodice/cviceni-vyjmenovana-slova-b
export const dictionary = [
  { text: 'um_vadlo', valIdx: 0, correct: 'y' },
  { text: 'm_stní obyvatel', valIdx: 1, correct: 'í' },
  { text: 'm_lá paní', valIdx: 0, correct: 'i' },
  { text: 'moje mam_nka', valIdx: 0, correct: 'i' },
  { text: 'dávná m_nulost', valIdx: 0, correct: 'i' },
  { text: 'těžký prům_sl', valIdx: 0, correct: 'y' },
  { text: 'usm_vá se na mě', valIdx: 1, correct: 'í' },
  { text: 'm_je nádobí', valIdx: 0, correct: 'y' },
  { text: 'velká m_stnost', valIdx: 1, correct: 'í' },
  { text: 'čerstvá om_tka', valIdx: 1, correct: 'í' },
  { text: 'zam_chej polévku', valIdx: 1, correct: 'í' },
  { text: 'spolužák M_rek', valIdx: 0, correct: 'i' },
  { text: 'm_rný svah', valIdx: 1, correct: 'í' },
  { text: 'm_slivecká puška', valIdx: 0, correct: 'y' },
  { text: 'vym_šlet pohádky', valIdx: 1, correct: 'ý' },
  { text: 'užitečný hm_z', valIdx: 0, correct: 'y' },
  { text: 'skvělá m_šlenka', valIdx: 0, correct: 'y' },
  { text: 'hlem_ždí ulita', valIdx: 1, correct: 'ý' },
  { text: 'neum_me zpívat', valIdx: 1, correct: 'í' },
  { text: 'pěkná m_ska', valIdx: 0, correct: 'i' },
  { text: 'malá m_stička', valIdx: 0, correct: 'i' },
  { text: 'm_sto ve vlaku', valIdx: 1, correct: 'í' },
  { text: 'velký nesm_sl', valIdx: 0, correct: 'y' },
  { text: 'bílé m_šky', valIdx: 0, correct: 'y' },
  { text: 'svědom_tý spolužák', valIdx: 0, correct: 'i' },
  { text: 'M_lena maluje', valIdx: 0, correct: 'i' },
  { text: 'nam_dli si ruce', valIdx: 0, correct: 'y' },
  { text: 'm_slivna na samotě', valIdx: 0, correct: 'y' },
  { text: 'm_rná zima', valIdx: 1, correct: 'í' },
  { text: 'Přem_sl', valIdx: 0, correct: 'y' },
  { text: 'Křesom_sl', valIdx: 0, correct: 'y' },
  { text: 'hodný m_slivec', valIdx: 0, correct: 'y' },
  { text: 'zam_řil ke mně', valIdx: 1, correct: 'í' },
  { text: 'm_nistr práce', valIdx: 0, correct: 'i' },
  { text: 'um_š malovat', valIdx: 1, correct: 'í' },
  { text: 'na m_tině u lesa', valIdx: 1, correct: 'ý' },
  { text: 'm_nuli jsme se', valIdx: 0, correct: 'i' },
  { text: 'to nemá sm_sl', valIdx: 0, correct: 'y' },
  { text: 'pořád přem_šlet', valIdx: 1, correct: 'ý' },
  { text: 'Vysoké M_to', valIdx: 1, correct: 'ý' },
  { text: 'chm_ří pampelišky', valIdx: 1, correct: 'ý' },
  { text: 'dostat sm_k', valIdx: 0, correct: 'y' },
  { text: 'světový m_r', valIdx: 1, correct: 'í' },
  { text: 'nové m_dlo', valIdx: 1, correct: 'ý' },
  { text: 'barevné m_dliny', valIdx: 0, correct: 'y' },
  { text: 'm_lá babičko', valIdx: 0, correct: 'i' },
  { text: 'není zlom_slný', valIdx: 0, correct: 'y' },
  { text: 'nová m_za', valIdx: 1, correct: 'í' },
  { text: 'm_šlenka', valIdx: 0, correct: 'y' },
  { text: 'malé sm_tko', valIdx: 1, correct: 'í' },
  { text: 'rozdm_chat oheň', valIdx: 1, correct: 'ý' },
  { text: 'všeho s m_rou', valIdx: 1, correct: 'í' },
  { text: 'm_slím na tebe', valIdx: 0, correct: 'y' },
  { text: 'zam_kej dveře', valIdx: 0, correct: 'y' },
  { text: 'vým_k na hrazdě', valIdx: 0, correct: 'y' },
  { text: 'sm_čka na laně', valIdx: 0, correct: 'y' },
  { text: 'kytice jasm_nu', valIdx: 1, correct: 'í' },
  { text: 'modrý m_č', valIdx: 1, correct: 'í' },
  { text: 'osm_čka', valIdx: 0, correct: 'i' },
  { text: 'malá M_luška', valIdx: 0, correct: 'i' },
  { text: 'neum_té nohy', valIdx: 0, correct: 'y' },
  { text: 'hlasitý sm_ch', valIdx: 1, correct: 'í' },
  { text: 'lesklý kam_nek', valIdx: 1, correct: 'í' },
  { text: 'malé sem_nko', valIdx: 1, correct: 'í' },
  { text: 'M_lada Horáková', valIdx: 0, correct: 'i' },
  { text: 'm_chaná vajíčka', valIdx: 1, correct: 'í' },
  { text: 'dotěrný hm_z', valIdx: 0, correct: 'y' },
  { text: 'velký om_l', valIdx: 0, correct: 'y' },
  { text: 'rozum_m německy', valIdx: 1, correct: 'í' },
  { text: 'děti se m_jí vodou', valIdx: 0, correct: 'y' },
  { text: 'm_str světa', valIdx: 0, correct: 'i' },
  { text: 'nem_lá návštěva', valIdx: 0, correct: 'i' },
  { text: 'dom_šlivá dívka', valIdx: 1, correct: 'ý' },
  { text: 'km_nek jabloně', valIdx: 1, correct: 'í' },
  { text: 'vzpom_nka na léto', valIdx: 1, correct: 'í' },
  { text: 'prom_ňte', valIdx: 0, correct: 'i' },
  { text: 'nam_řená zbraň', valIdx: 1, correct: 'í' },
  { text: 'nedaleká m_tina', valIdx: 1, correct: 'ý' },
  { text: 'zam_kejte bránu', valIdx: 0, correct: 'y' },
  { text: 'nachom_tl se', valIdx: 1, correct: 'ý' },
  { text: 'm_slili jsme', valIdx: 0, correct: 'y' },
  { text: 'je můj m_láček', valIdx: 0, correct: 'i' },
  { text: 'pom_chané karty', valIdx: 1, correct: 'í' },
  { text: 'hlem_ždí tempo', valIdx: 1, correct: 'ý' },
  { text: 'nesm_kej s tím', valIdx: 1, correct: 'ý' },
  { text: 'foukal do chm_ří', valIdx: 1, correct: 'ý' },
  { text: 'm_slivecký klobouk', valIdx: 0, correct: 'y' },
  { text: 'hm_zí bzukot', valIdx: 0, correct: 'y' },
  { text: 'zlý úm_sl', valIdx: 0, correct: 'y' },
  { text: 'Jarm_la', valIdx: 0, correct: 'i' },
  { text: 'Kam_la', valIdx: 0, correct: 'i' },
  { text: 'Jana se m_lila', valIdx: 1, correct: 'ý' },
  { text: 'M_lan', valIdx: 0, correct: 'i' },
  { text: 'Petr nezam_ká', valIdx: 0, correct: 'y' },
  { text: 'přiznal jsem om_l', valIdx: 0, correct: 'y' },
  { text: 'sním m_sku jahod', valIdx: 0, correct: 'i' },
  { text: 'zm_je je had', valIdx: 0, correct: 'i' },
  { text: 'm_t štěstí', valIdx: 1, correct: 'í' },
  { text: 'm_jet se na cestě', valIdx: 1, correct: 'í' },
];

const View = ({ options }) => (<div className="problem">{dictionary[options.i].text}</div>);

// method of selecting questions: 0: pick from 'wrong' array, 1: pick from 'slow' array, 2: generate new
// method with higher number is always fallback for the current one
const methods = [0, 0, 1, 2];

export const wIYm = new Module({
  routeName: 'w-iy-m-2',
  title: 'i/y po M',
  subtitle: 'vyjmenovaná slova',
  onActivate: onModuleActivate,
  next: createNext(dictionary, methods),
  View,
  correctResp: ({ i }) => (dictionary[i].correct),
  choices: ({ i }) => (values[dictionary[i].valIdx]),
});
