import React from 'react';
import { Module } from '../../../core/module';
import { onModuleActivate } from '../../utils';
import { createNext } from './utils';

const values = [
  { val1: 'i', val2: 'y' },
  { val1: 'í', val2: 'ý' },
];

// http://www.zlobidlo.cz/rodice/cviceni-vyjmenovana-slova-p
export const dictionary = [
  { text: 'netop_ří tělo', valIdx: 1, correct: 'ý' },
  { text: 'hraju si na p_sku', valIdx: 1, correct: 'í' },
  { text: 'p_tel brambor', valIdx: 0, correct: 'y' },
  { text: 'trn p_chá', valIdx: 1, correct: 'í' },
  { text: 'slep_me papír', valIdx: 1, correct: 'í' },
  { text: 'slepíme pap_r', valIdx: 1, correct: 'í' },
  { text: 'lep_dlo na papír', valIdx: 0, correct: 'i' },
  { text: 'p_l lučního kvítí', valIdx: 0, correct: 'y' },
  { text: 'malá op_čka', valIdx: 0, correct: 'i' },
  { text: 'p_šný jako páv', valIdx: 0, correct: 'y' },
  { text: 'brněnský p_vovar', valIdx: 0, correct: 'i' },
  { text: 'koňské kop_to', valIdx: 0, correct: 'y' },
  { text: 'velké p_smeno', valIdx: 1, correct: 'í' },
  { text: 'p_lná studentka', valIdx: 0, correct: 'i' },
  { text: 'plachý slep_š', valIdx: 1, correct: 'ý' },
  { text: 'p_tlák v lese', valIdx: 0, correct: 'y' },
  { text: 'rosa se třp_tila', valIdx: 0, correct: 'y' },
  { text: 'načep_řený krocan', valIdx: 1, correct: 'ý' },
  { text: 'látkový p_tlík', valIdx: 0, correct: 'y' },
  { text: 'chlapci klop_tali', valIdx: 1, correct: 'ý' },
  { text: 'napiš dop_s', valIdx: 0, correct: 'i' },
  { text: 'nap_š dopis', valIdx: 0, correct: 'i' },
  { text: 'časop_sy a noviny', valIdx: 0, correct: 'i' },
  { text: 'pop_navá rostlina', valIdx: 1, correct: 'í' },
  { text: 'koup_t si', valIdx: 0, correct: 'i' },
  { text: 'p_tlík bonbónů', valIdx: 0, correct: 'y' },
  { text: 'na poli roste p_r', valIdx: 1, correct: 'ý' },
  { text: 'heboučké p_rko', valIdx: 1, correct: 'í' },
  { text: 'p_škotové těsto', valIdx: 0, correct: 'i' },
  { text: 'p_skni na něho', valIdx: 1, correct: 'í' },
  { text: 'p_sečná pláž', valIdx: 1, correct: 'í' },
  { text: 'nap_navá kniha', valIdx: 1, correct: 'í' },
  { text: 'odp_kat si trest', valIdx: 0, correct: 'y' },
  { text: 'řetízek se třp_til', valIdx: 0, correct: 'y' },
  { text: 'nepij p_vo', valIdx: 0, correct: 'i' },
  { text: 'nep_j pivo', valIdx: 0, correct: 'i' },
  { text: 'přep_chový palác', valIdx: 0, correct: 'y' },
  { text: 'suché p_liny', valIdx: 0, correct: 'i' },
  { text: 'starý sp_s', valIdx: 0, correct: 'i' },
  { text: 'p_lná hospodyňka', valIdx: 0, correct: 'i' },
  { text: 'dívka p_ští', valIdx: 0, correct: 'i' },
  { text: 'podej mi p_lník', valIdx: 0, correct: 'i' },
  { text: 'p_la na dřevo', valIdx: 0, correct: 'i' },
  { text: 'p_šeme na počítači', valIdx: 1, correct: 'í' },
  { text: 'papírový p_tlík', valIdx: 0, correct: 'y' },
  { text: 'pap_rový pytlík', valIdx: 1, correct: 'í' },
  { text: 'Pep_k', valIdx: 1, correct: 'í' },
  { text: 'nap_ná šňůru', valIdx: 1, correct: 'í' },
  { text: 'osel má p_sk', valIdx: 0, correct: 'y' },
  { text: 'krocan se čep_ří', valIdx: 1, correct: 'ý' },
  { text: 'žlutý p_l', valIdx: 0, correct: 'y' },
  { text: 'slep_ce na paprice', valIdx: 0, correct: 'i' },
  { text: 'hrad z p_sku', valIdx: 1, correct: 'í' },
  { text: 'nap_š celou větu', valIdx: 0, correct: 'i' },
  { text: 'líný slep_š', valIdx: 1, correct: 'ý' },
  { text: 'velký netop_r', valIdx: 1, correct: 'ý' },
  { text: 'klop_tla o balvan', valIdx: 1, correct: 'ý' },
  { text: 'šp_navé kalhoty', valIdx: 0, correct: 'i' },
  { text: 'p_chlavé trny', valIdx: 0, correct: 'i' },
  { text: 'zp_tovat svědomí', valIdx: 0, correct: 'y' },
  { text: 'urostlý chlap_k', valIdx: 1, correct: 'í' },
  { text: 'jemný p_lník', valIdx: 0, correct: 'i' },
  { text: 'nep_skej na psa', valIdx: 1, correct: 'í' },
  { text: 'výp_sky z knih', valIdx: 0, correct: 'i' },
  { text: 'zp_váme rádi', valIdx: 1, correct: 'í' },
  { text: 'veselé p_sničky', valIdx: 1, correct: 'í' },
  { text: 'včely jsou p_lné', valIdx: 0, correct: 'i' },
  { text: 'p_tel brambor', valIdx: 0, correct: 'y' },
  { text: 'zp_tuje svědomí', valIdx: 0, correct: 'y' },
  { text: 'rozkvetlá p_voňka', valIdx: 0, correct: 'i' },
  { text: 'op_čí mládě', valIdx: 0, correct: 'i' },
  { text: 'zatřp_tila se', valIdx: 0, correct: 'y' },
  { text: 'p_ská na prsty', valIdx: 1, correct: 'í' },
  { text: 'čertovo kop_tko', valIdx: 1, correct: 'ý' },
  { text: 'poraněný p_sk', valIdx: 0, correct: 'y' },
  { text: 'slepice se čep_ří', valIdx: 1, correct: 'ý' },
  { text: 'p_chnout se o trn', valIdx: 1, correct: 'í' },
  { text: 'kapky se třp_tily', valIdx: 0, correct: 'y' },
  { text: 'p_sklavý hlásek', valIdx: 0, correct: 'i' },
  { text: 'nap_nat lano', valIdx: 1, correct: 'í' },
  { text: 'smrkové p_liny', valIdx: 0, correct: 'i' },
  { text: 'p_tlovina', valIdx: 0, correct: 'y' },
  { text: 'nep_tlačte v lese', valIdx: 0, correct: 'y' },
  { text: 'malé kop_tko', valIdx: 1, correct: 'ý' },
  { text: 'vytrvalost a p_le', valIdx: 1, correct: 'í' },
  { text: 'mládě p_palo', valIdx: 1, correct: 'í' },
  { text: 'kluk se nap_l vody', valIdx: 0, correct: 'i' },
  { text: 'nevyp_nej se', valIdx: 1, correct: 'í' },
  { text: 'p_šeme pohledy', valIdx: 1, correct: 'í' },
  { text: 'přep_š ten text', valIdx: 0, correct: 'i' },
  { text: 'vrbová p_šťalka', valIdx: 1, correct: 'í' },
  { text: 'lidová p_seň', valIdx: 1, correct: 'í' },
  { text: 'starý pap_r', valIdx: 1, correct: 'í' },
  { text: 'zalep_l obálku', valIdx: 0, correct: 'i' },
  { text: 'koně klop_tali', valIdx: 1, correct: 'ý' },
  { text: 'růže p_chá', valIdx: 1, correct: 'í' },
  { text: 'P_šná princezna', valIdx: 0, correct: 'y' },
  { text: 'p_kat za své činy', valIdx: 0, correct: 'y' },
  { text: 'Pep_ček je hodný', valIdx: 1, correct: 'í' },
  { text: 'topoly se vyp_nají', valIdx: 1, correct: 'í' },
  { text: 'přep_chové auto', valIdx: 0, correct: 'y' },
  { text: 'přilep to lep_dlem', valIdx: 0, correct: 'i' },
  { text: 'pevně to přilep_š', valIdx: 1, correct: 'í' },
  { text: 'dřevěné p_liny', valIdx: 0, correct: 'i' },
  { text: 'posp_chej pomalu', valIdx: 1, correct: 'í' },
  { text: 'nap_navý film', valIdx: 1, correct: 'í' },
  { text: 'vrabci se čep_řili', valIdx: 1, correct: 'ý' },
  { text: 'netop_ří let', valIdx: 1, correct: 'ý' },
  { text: 'p_rátská loď', valIdx: 0, correct: 'i' },
];

const View = ({ options }) => (<div className="problem">{dictionary[options.i].text}</div>);

// method of selecting questions: 0: pick from 'wrong' array, 1: pick from 'slow' array, 2: generate new
// method with higher number is always fallback for the current one
const methods = [0, 0, 1, 2];

export const wIYp = new Module({
  routeName: 'w-iy-p-3',
  title: 'i/y po P',
  subtitle: 'vyjmenovaná slova',
  onActivate: onModuleActivate,
  next: createNext(dictionary, methods),
  View,
  correctResp: ({ i }) => (dictionary[i].correct),
  choices: ({ i }) => (values[dictionary[i].valIdx]),
});
