import React from 'react';
import { Module } from '../../../core/module';
import { onModuleActivate } from '../../utils';
import { createNext } from './utils';

const values = [
  { val1: 'i', val2: 'y' },
  { val1: 'í', val2: 'ý' },
];

// http://www.zlobidlo.cz/rodice/cviceni-vyjmenovana-slova-l
const dictionary = [
  { text: 'l_ška Bystrouška', valIdx: 0, correct: 'i' },
  { text: 'vel_ká lampa', valIdx: 0, correct: 'i' },
  { text: 'strom l_pa', valIdx: 1, correct: 'í' },
  { text: 'poraněné l_tko', valIdx: 1, correct: 'ý' },
  { text: 'sl_šela jsem', valIdx: 0, correct: 'y' },
  { text: 'kamarád L_bor', valIdx: 0, correct: 'i' },
  { text: 'nejbl_žší dvůr', valIdx: 0, correct: 'i' },
  { text: 'starý ml_n', valIdx: 1, correct: 'ý' },
  { text: 'sestra Ol_na', valIdx: 0, correct: 'i' },
  { text: 'venku se bl_skalo', valIdx: 1, correct: 'ý' },
  { text: 'čas neupl_nul', valIdx: 0, correct: 'y' },
  { text: 'bl_skavé předměty', valIdx: 1, correct: 'ý' },
  { text: 'l_žuj opatrně', valIdx: 0, correct: 'y' },
  { text: 'miminko vzl_kalo', valIdx: 0, correct: 'y' },
  { text: 'l_tostivá Anna', valIdx: 1, correct: 'í' },
  { text: 'nedočkavá L_da', valIdx: 1, correct: 'í' },
  { text: 'kl_če od domu', valIdx: 1, correct: 'í' },
  { text: 'l_ný Honza', valIdx: 1, correct: 'í' },
  { text: 'starý ml_nář', valIdx: 0, correct: 'y' },
  { text: 'vel_ké oči', valIdx: 0, correct: 'i' },
  { text: 'nedosl_chavý pes', valIdx: 1, correct: 'ý' },
  { text: 'nepl_tvej časem', valIdx: 1, correct: 'ý' },
  { text: 'pes se l_sá', valIdx: 1, correct: 'í' },
  { text: 'l_zat zmrzlinu', valIdx: 1, correct: 'í' },
  { text: 'L_sá hora', valIdx: 0, correct: 'y' },
  { text: 'pol_kej pomalu', valIdx: 0, correct: 'y' },
  { text: 'l_dský výtvor', valIdx: 0, correct: 'i' },
  { text: 'vyl_čený pokoj', valIdx: 1, correct: 'í' },
  { text: 'voňavý pel_něk', valIdx: 0, correct: 'y' },
  { text: 'obl_bený film', valIdx: 1, correct: 'í' },
  { text: 'zal_vat kytky', valIdx: 1, correct: 'í' },
  { text: 'seml_t mák', valIdx: 1, correct: 'í' },
  { text: 'l_sá hlava', valIdx: 0, correct: 'y' },
  { text: 'pevné l_ko', valIdx: 1, correct: 'ý' },
  { text: 'l_ska kvete', valIdx: 1, correct: 'í' },
  { text: 'pl_novod', valIdx: 0, correct: 'y' },
  { text: 'kl_dná řeka', valIdx: 0, correct: 'i' },
  { text: 'upl_nulý týden', valIdx: 0, correct: 'y' },
  { text: 'sl_ším hrom', valIdx: 0, correct: 'y' },
  { text: 'pl_seň v domě', valIdx: 1, correct: 'í' },
  { text: 'pl_šová hračka', valIdx: 0, correct: 'y' },
  { text: 'zákeřný l_kožrout', valIdx: 1, correct: 'ý' },
  { text: 'nesl_šně našlapuje', valIdx: 0, correct: 'y' },
  { text: 'pomalu se pl_ží', valIdx: 1, correct: 'í' },
  { text: 'bl_zko domu', valIdx: 1, correct: 'í' },
  { text: 'nel_tuj se', valIdx: 0, correct: 'i' },
  { text: 'l_s na ovoce', valIdx: 0, correct: 'i' },
  { text: 'L_sá nad Labem', valIdx: 0, correct: 'y' },
  { text: 'obě l_tka', valIdx: 1, correct: 'ý' },
  { text: 'králík kl_čkuje', valIdx: 0, correct: 'i' },
  { text: 'l_žařská výbava', valIdx: 0, correct: 'y' },
  { text: 'pl_noucí voda', valIdx: 0, correct: 'y' },
  { text: 'pl_nový vařič', valIdx: 0, correct: 'y' },
  { text: 'had pol_ká žábu', valIdx: 0, correct: 'y' },
  { text: 'bl_štivé sklo', valIdx: 0, correct: 'y' },
  { text: 'l_ska je pták', valIdx: 0, correct: 'y' },
  { text: 'l_ska je strom', valIdx: 1, correct: 'í' },
  { text: 'l_bivé kalhoty', valIdx: 1, correct: 'í' },
  { text: 'prudký l_ják', valIdx: 0, correct: 'i' },
  { text: 'tiše se přibl_žit', valIdx: 1, correct: 'í' },
  { text: 'ml_nské kolo', valIdx: 1, correct: 'ý' },
  { text: 'voda pl_nula pomalu', valIdx: 0, correct: 'y' },
  { text: 'l_né odpoledne', valIdx: 1, correct: 'í' },
  { text: 'l_čit past na myši', valIdx: 1, correct: 'í' },
  { text: 'l_bila se mi', valIdx: 1, correct: 'í' },
  { text: 'l_pový květ', valIdx: 0, correct: 'i' },
  { text: 'pel_ňkový čaj', valIdx: 0, correct: 'y' },
  { text: 'pl_š je látka', valIdx: 0, correct: 'y' },
  { text: 'zabl_sklo se', valIdx: 1, correct: 'ý' },
  { text: 'na l_stech', valIdx: 0, correct: 'i' },
  { text: 'l_zat nanuk', valIdx: 0, correct: 'i' },
  { text: 'l_ščí ohon', valIdx: 0, correct: 'i' },
  { text: 'l_tostivý pohled', valIdx: 1, correct: 'í' },
  { text: 'tichý vzl_kot', valIdx: 0, correct: 'y' },
  { text: 'rozpl_ne se', valIdx: 0, correct: 'y' },
  { text: 'svítipl_n', valIdx: 0, correct: 'y' },
  { text: 'L_tomyšl', valIdx: 0, correct: 'i' },
  { text: 'upl_nula řada let', valIdx: 0, correct: 'y' },
  { text: 'nesl_ším hudbu', valIdx: 0, correct: 'y' },
  { text: 'malá kl_cka', valIdx: 1, correct: 'í' },
  { text: 'mám l_sinu', valIdx: 0, correct: 'y' },
  { text: 'ml_nářský pomocník', valIdx: 0, correct: 'y' },
  { text: 'l_dové písně', valIdx: 0, correct: 'i' },
  { text: 'je to bl_zoučko', valIdx: 0, correct: 'i' },
  { text: 'l_st papíru', valIdx: 0, correct: 'i' },
  { text: 'pl_šový kabátek', valIdx: 0, correct: 'y' },
  { text: 'odvar z pel_ňku', valIdx: 0, correct: 'y' },
  { text: 'ml_nek na kávu', valIdx: 1, correct: 'ý' },
  { text: 'taška z l_ka', valIdx: 1, correct: 'ý' },
  { text: 'noční hl_dka', valIdx: 1, correct: 'í' },
  { text: 'kněžna L_buše', valIdx: 0, correct: 'i' },
  { text: 'zemní pl_n', valIdx: 0, correct: 'y' },
  { text: 'dcera L_duška', valIdx: 0, correct: 'i' },
  { text: 'malý kl_č', valIdx: 1, correct: 'í' },
  { text: 'obilný kl_ček', valIdx: 1, correct: 'í' },
  { text: 'l_že med', valIdx: 1, correct: 'í' },
  { text: 'hvězdy se bl_skaly', valIdx: 1, correct: 'ý' },
];

const View = ({ options }) => (<div className="problem">{dictionary[options.i].text}</div>);

// method of selecting questions: 0: pick from 'wrong' array, 1: pick from 'slow' array, 2: generate new
// method with higher number is always fallback for the current one
const methods = [0, 0, 1, 2];

export const wIYl = new Module({
  routeName: 'w-iy-l',
  title: 'i/y po L',
  subtitle: 'vyjmenovaná slova',
  onActivate: onModuleActivate,
  next: createNext(dictionary, values, methods),
  View,
});
